name = "cf-worker-id-dev" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"


[vars]
# UUID = "6baea179-0f18-4c98-a4a1-44c740d30cff"
# PROXYIP = "172.232.238.169"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "fbd2ae08-ebe9-49c2-ad02-9c47db0b84a7"
